# Generated by Django 4.2.10 on 2024-02-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(help_text='The notification message')),
                ('schedule', models.CharField(blank=True, help_text='Represents a crontab value. If null, the notification will directly be sent once.', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], max_length=10)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
