apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-deployment
  name: api-service
  namespace: default
  resourceVersion: "35934"
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.8.111
  clusterIPs:
  - 10.98.8.111
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32189
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: api-deployment
  sessionAffinity: None
  type: LoadBalancer
